"""Tests for setup wizard shared logic."""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 — used at runtime by pytest

from clanker.setup.wizard import (
    generate_config,
    generate_env,
    infer_rooms,
    save_config,
)


def test_generate_config_basic() -> None:
    answers = {
        "ha_url": "http://localhost:8123",
        "anthropic_enabled": True,
        "anthropic_model": "claude-sonnet-4-20250514",
        "ollama_enabled": True,
        "ollama_url": "http://localhost:11434",
        "ollama_model": "llama3.2",
        "default_provider": "anthropic",
        "task_routes": {
            "vision": "anthropic",
            "quick_intent": "ollama",
        },
    }
    yaml_content = generate_config(answers)
    assert "ha:" in yaml_content
    assert "anthropic:" in yaml_content
    assert "ollama:" in yaml_content
    assert "default_provider: anthropic" in yaml_content
    assert "task_routes:" in yaml_content


def test_generate_config_with_frigate() -> None:
    answers = {
        "ha_url": "http://localhost:8123",
        "default_provider": "anthropic",
        "frigate_enabled": True,
        "frigate_url": "http://localhost:5000",
    }
    yaml_content = generate_config(answers)
    assert "frigate:" in yaml_content
    assert "enabled: true" in yaml_content


def test_generate_config_no_providers() -> None:
    answers = {"ha_url": "http://localhost:8123", "default_provider": "anthropic"}
    yaml_content = generate_config(answers)
    assert "ha:" in yaml_content
    assert "anthropic:" not in yaml_content  # not enabled


def test_generate_env() -> None:
    answers = {
        "ha_token": "my-token",
        "anthropic_key": "sk-ant-123",
    }
    env_content = generate_env(answers)
    assert "CLANKER_HA__TOKEN=my-token" in env_content
    assert "CLANKER_ANTHROPIC__API_KEY=sk-ant-123" in env_content


def test_generate_env_no_keys() -> None:
    env_content = generate_env({})
    assert "Generated by clanker-setup" in env_content


def test_infer_rooms() -> None:
    entities = {
        "speakers": [
            {"entity_id": "media_player.living_room_speaker", "name": "Living Room"},
            {"entity_id": "media_player.kitchen_speaker", "name": "Kitchen"},
        ],
        "occupancy_sensors": [
            {"entity_id": "binary_sensor.living_room_occupancy", "name": "LR Occ"},
        ],
        "motion_sensors": [],
    }
    rooms = infer_rooms(entities)
    assert "living_room" in rooms
    assert "kitchen" in rooms


def test_infer_rooms_empty() -> None:
    assert infer_rooms({}) == []


def test_save_config(tmp_path: Path) -> None:
    config_dir = tmp_path / "config"
    paths = save_config(
        "ha:\n  url: test\n",
        "TOKEN=abc\n",
        config_dir=config_dir,
        project_dir=tmp_path,
    )
    assert (config_dir / "clanker.yaml").read_text() == "ha:\n  url: test\n"
    assert (tmp_path / ".env").read_text() == "TOKEN=abc\n"
    assert "yaml" in paths
    assert "env" in paths
